name: CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Replace toc-versions
        uses: Numynum/ToCVersions@master
        with:
          args: FixTransmogOutfits.toc

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: -p 366173
